config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :shops do
    resources :reviews, only: [:index, :create] do
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many :favorites, dependent: :destroy

  validates :score, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reviews, dependent: :destroy
  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :username,presence: true

  def already_favorited?(review)
    favorites.exists?(review_id: review.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(_resource)
    shops_path
  end

  def after_sign_in_path_for(_resource)
    shops_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    if current_user.id != @review.user_id
      @favorite = current_user.favorites.create(review_id: params[:review_id])
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @review = Review.find(params[:review_id])
    @favorite = current_user.favorites.find_by(review_id: @review.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @shop = Shop.find(params[:shop_id])
    @reviews = @shop.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to shop_reviews_path(@review.shop)
    else
      @shop = Shop.find(params[:shop_id])
      render 'shops/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:shop_id, :score, :content)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/homes/top.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
          <p class="is-size-1 has-text-weight-bold has-text-centered">Post a review</p>
          <br>
          <div class="columns is-centered">
            <div class="column is-3">
              <%= link_to "List of stores", shops_path, class: "button is-fullwidth" %>
              <br>
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-fullwidth" %>
              <% else %>
                <%= link_to "Log in", new_user_session_path, class: "button is-fullwidth" %>
                <br>
                <%= link_to "Sign up", new_user_registration_path, class: "button is-fullwidth" %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-3 ml-3" style="font-family: serif; color: black;">review</strong>
          <% end %>
        </p>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to shops_path, class: "navbar-item" do %>
            List of stores
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ<%= current_user.username %>さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  Log Out
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  Log in
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  Sign Up
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">Let's review</p>
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="rating-box mt-3">
  <%= form_with model: review, url: shop_reviews_path(shop), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3 ">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :shop_id, value: shop.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "Save", class: "button mt-3" %>
    <%= link_to "See other reviews", shop_reviews_path(shop), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card mb-6 box">
          <header class="card-header">
            <p class="card-header-title">
              <%= @shop.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width:<%= @shop.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @shop.avg_score %>points（<%= @shop.reviews.count %>reviews）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>user</th><th>score</th><th>content</th><th>good</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
                <td>
                <% if user_signed_in? %>
                  <% if current_user.already_favorited?(review) %>
                    <%= link_to shop_review_favorites_path(@shop.id,review), method: :delete do %>
                      <i class="fas fa-heart heart_red"></i>
                    <% end %>
                    <%= review.favorites.count %>
                  <% else %>
                    <%= link_to shop_review_favorites_path(@shop.id,review), method: :post do %>
                      <i class="far fa-heart heart_red"></i>
                    <% end %>
                    <%= review.favorites.count %>
                  <% end %>
                <% else %>
                  <i class="far fa-heart heart_red"></i>
                  <%= review.favorites.count %>
                <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/shops/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <% @shops.each do |shop| %>
          <div class="box mb-4">
            <header class="card-header">
              <p class="card-header-title">
                <%= shop.name %>
              </p>
            </header>
            <div class="card-content">
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: <%= shop.review_score_percentage %>%">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                    <%= shop.avg_score %>points（<%= shop.reviews.count %>reviews）                    
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
              <%= link_to shop_reviews_path(shop), class: "button card-footer-item" do %>
                check the review
              <% end %>
              <%= link_to shop_path(shop), class: "button card-footer-item" do %>
                write a review
              <% end %>
            </footer>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shops/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card mb-6 box">
          <header class="card-header">
            <p class="card-header-title">
              <%= @shop.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @shop.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @shop.avg_score %>points（<%= @shop.reviews.count %>reviews）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, shop: @shop %>
      </div>
    </div>
  </div>
</section>